issue-111: Add reward amount to the qr-code service
SatorNetwork/sator-api pull request #36
Opened 2021-06-14 11:31 UTC by ValeriiLav

2021-06-15 08:01 UTC, dmitrymomot requested changes

2021-06-15 08:01 UTC, dmitrymomot commented on svc/qrcodes/service.go
> +		err := s.rs.AddDepositTransaction(ctx, userID, qrcodeData.RewardAmount.Float64, qrcodeID, "??")
?? = table name = `qrcodes`

2021-06-15 08:27 UTC, dmitrymomot approved these changes

2021-06-15 08:28 UTC, dmitrymomot commented
waiting for [SAT-121](https://nftprojectsboosty.atlassian.net/browse/SAT-121) will be completed

2021-06-15 10:20 UTC, ValeriiLav commented on svc/qrcodes/service.go
> +		AddDepositTransaction(ctx context.Context, userID uuid.UUID, amount float64, relationID uuid.UUID, relationType string) error
AddDepositTransaction(ctx context.Context, userID, relationID uuid.UUID, relationType string, amount float64) error

2021-06-16 13:53 UTC, ValeriiLav commented on svc/qrcodes/service.go
> +		err := s.rs.AddDepositTransaction(ctx, userID, qrcodeID, "qrcodes", qrcodeData.RewardAmount.Float64)
Move qrcodes to const.

2021-06-16 13:54 UTC, ValeriiLav commented on svc/qrcodes/service.go
> +		err := s.rs.AddDepositTransaction(ctx, userID, qrcodeID, "qrcodes", qrcodeData.RewardAmount.Float64)
// RelationTypeQrcodes indicates that relation type "qrcodes".
	RelationTypeQrcodes = "qrcodes"

2021-06-17 04:48 UTC, dmitrymomot approved these changes

2021-06-17 04:48 UTC, merged