sat-141: [api] Show episodes
SatorNetwork/sator-api pull request #49
Opened 2021-06-24 11:33 UTC by ValeriiLav

2021-06-24 11:35 UTC, ValeriiLav commented on svc/shows/repository/sql/migrations/20210624133925-create_episodes_table.sql
> +    episode_number INT NOT NULL DEFAULT 0,
@dmitrymomot please check is it right type

2021-06-24 14:05 UTC, dmitrymomot requested changes

2021-06-29 09:33 UTC, dmitrymomot requested changes

2021-06-29 09:33 UTC, dmitrymomot commented on svc/shows/repository/sql/migrations/20210624133925-create_episodes_table.sql
> +    PRIMARY KEY(id, show_id)
```suggestion

```

2021-06-29 09:33 UTC, dmitrymomot commented on svc/shows/repository/sql/migrations/20210624133925-create_episodes_table.sql
> +    id uuid NOT NULL,
```suggestion
id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
```

2021-06-29 09:49 UTC, dmitrymomot approved these changes

2021-06-29 09:50 UTC, merged