sat-166: Add description for show entity
SatorNetwork/sator-api pull request #57
Opened 2021-07-05 09:52 UTC by ValeriiLav

2021-07-05 13:40 UTC, Qweder93 commented on svc/shows/repository/sql/migrations/20210705122558-add_description_field.sql
> +ALTER TABLE shows DROP COLUMN category;
should drop description

2021-07-05 13:41 UTC, Qweder93 commented
rest looks nice

2021-07-05 14:57 UTC, dmitrymomot commented on svc/shows/repository/sql/migrations/20210705122558-add_description_field.sql
> +ALTER TABLE shows DROP COLUMN category;
@ValeriiLav ^^^

2021-07-06 02:25 UTC, dmitrymomot requested changes

2021-07-06 02:25 UTC, dmitrymomot commented on svc/shows/service.go
> +			Valid:  true,
```suggestion
			Valid: len(sh.Description) > 0,
```

2021-07-06 02:25 UTC, dmitrymomot commented on svc/shows/service.go
> +			Valid:  true,
```suggestion
			Valid: len(sh.Description) > 0,
```

2021-07-06 02:25 UTC, dmitrymomot commented on svc/shows/transport.go
>  		Cover:         r.URL.Query().Get(cover),
Use HTTP methods according to REST. 
- add = POST
- update whole entity = PUT
- update partially = PATCH
All these methods have a body, and payload must be taken from it

2021-07-06 12:45 UTC, ValeriiLav commented on svc/shows/transport.go
> +	if showID == "" {
fix it

2021-07-06 12:46 UTC, ValeriiLav commented on svc/shows/transport.go
> +	r.Get("/{show_id}/episodes/{episodes_id}}", httptransport.NewServer(
episode_id

2021-07-06 12:47 UTC, ValeriiLav commented on svc/shows/transport.go
> +	if showID == "" {
if episodeID == "" {

2021-07-06 12:49 UTC, dmitrymomot requested changes
pls fix syntax errors

2021-07-06 14:02 UTC, dmitrymomot approved these changes

2021-07-06 14:02 UTC, merged